### ISSUE TITLE
The K0709-22/1 group and I believe the repository used dreadful commits

### ISSUE THREAD

**Issue by tofickbrodaga** [siriusdevs/taxi_K0711-23#1]
![photo_2023-10-31 11 18 44](https://github.com/siriusdevs/taxi/assets/101170461/a181de3c-a1a6-4a56-88b6-280ebbda0ac7)

Pls rename commit, you're setting a bad example for us.

:(

**Comment by siriusdevs** [comment]
repo name changed to taxi_K0711-23
